version: "3"
services:
  artemis:
    image: vromero/activemq-artemis:2.16.0
    environment:
      ARTEMIS_MIN_MEMORY: 1024M
      ARTEMIS_MAX_MEMORY: 2048M
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - artemis:/var/lib/artemis
      - ./artemis/:/var/lib/artemis/etc-override/

volumes:
  artemis: