spring:
  application.name: jpa-example
  main.banner-mode: off
  jmx.enabled: false
  artemis:
    mode: native
    broker-url: ${broker-url:tcp://127.0.0.1:61616}
    user: ${broker-username:admin}
    password: ${broker-password:admin}

server:
  port: 8080
  error:
    whitelabel:
      enabled: true

messaging:
  queue-name: my-queue