spring:
  application.name: jpa-example
  main.banner-mode: off
  jmx.enabled: false
  artemis:
    mode: native
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin

server:
  port: 8080
  error:
    whitelabel:
      enabled: true